import { ABIDataTypes, BitcoinAbiTypes, OP_NET_ABI } from 'opnet';

export const BridgeDepositoryEvents = [
    {
        name: 'WrappedTokenSet',
        values: [
            { name: 'wrappedToken', type: ABIDataTypes.ADDRESS },
            { name: 'enabled', type: ABIDataTypes.BOOL },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'SignerRotated',
        values: [
            { name: 'oldEpoch', type: ABIDataTypes.UINT32 },
            { name: 'newEpoch', type: ABIDataTypes.UINT32 },
            { name: 'newSignerHash', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'TokenModeSet',
        values: [
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'mode', type: ABIDataTypes.UINT32 },
            { name: 'evmCounterpart', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'FlowAdded',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'mode', type: ABIDataTypes.UINT32 },
            { name: 'evmChainId', type: ABIDataTypes.UINT64 },
            { name: 'evmToken', type: ABIDataTypes.UINT256 },
            { name: 'opnetToken', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'FlowStatusChanged',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'oldStatus', type: ABIDataTypes.UINT32 },
            { name: 'newStatus', type: ABIDataTypes.UINT32 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'FlowCapChanged',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'oldCap', type: ABIDataTypes.UINT256 },
            { name: 'newCap', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'FlowDailyLimitChanged',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'oldLimit', type: ABIDataTypes.UINT256 },
            { name: 'newLimit', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'FlowMinAmountChanged',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'oldMin', type: ABIDataTypes.UINT256 },
            { name: 'newMin', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'FlowFeeChanged',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'oldBps', type: ABIDataTypes.UINT32 },
            { name: 'newBps', type: ABIDataTypes.UINT32 },
            { name: 'oldMinFee', type: ABIDataTypes.UINT256 },
            { name: 'newMinFee', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'FlowTipCapUpdated',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'oldBps', type: ABIDataTypes.UINT32 },
            { name: 'newBps', type: ABIDataTypes.UINT32 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'LockedForBridge',
        values: [
            { name: 'canonicalToken', type: ABIDataTypes.ADDRESS },
            { name: 'user', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
            { name: 'evmRecipient', type: ABIDataTypes.UINT256 },
            { name: 'destChainId', type: ABIDataTypes.UINT32 },
            { name: 'lockNonce', type: ABIDataTypes.UINT256 },
            { name: 'mode', type: ABIDataTypes.UINT32 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'ReleasedFromVoucher',
        values: [
            { name: 'recipient', type: ABIDataTypes.ADDRESS },
            { name: 'canonicalToken', type: ABIDataTypes.ADDRESS },
            { name: 'sourceChainId', type: ABIDataTypes.UINT256 },
            { name: 'sourceTxHash', type: ABIDataTypes.UINT256 },
            { name: 'sourceLogIndex', type: ABIDataTypes.UINT32 },
            { name: 'grossAmount', type: ABIDataTypes.UINT256 },
            { name: 'feeAmount', type: ABIDataTypes.UINT256 },
            { name: 'netAmount', type: ABIDataTypes.UINT256 },
            { name: 'voucherId', type: ABIDataTypes.UINT256 },
            { name: 'signerEpoch', type: ABIDataTypes.UINT32 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'RelayerTipPaid',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'relayer', type: ABIDataTypes.ADDRESS },
            { name: 'tip', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'InventoryProvisionedOpNet',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'by', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'InventoryDrainedOpNet',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'to', type: ABIDataTypes.ADDRESS },
            { name: 'by', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'BurnConfirmed',
        values: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'depositId', type: ABIDataTypes.UINT256 },
            { name: 'releasedAmount', type: ABIDataTypes.UINT256 },
            { name: 'attester', type: ABIDataTypes.ADDRESS },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'Paused',
        values: [],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'Unpaused',
        values: [],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'GovernorUpdated',
        values: [
            { name: 'oldGov', type: ABIDataTypes.ADDRESS },
            { name: 'newGov', type: ABIDataTypes.ADDRESS },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'MintedFromVoucher',
        values: [
            { name: 'recipient', type: ABIDataTypes.ADDRESS },
            { name: 'wrappedToken', type: ABIDataTypes.ADDRESS },
            { name: 'sourceChainId', type: ABIDataTypes.UINT256 },
            { name: 'sourceTxHash', type: ABIDataTypes.UINT256 },
            { name: 'sourceLogIndex', type: ABIDataTypes.UINT32 },
            { name: 'grossAmount', type: ABIDataTypes.UINT256 },
            { name: 'feeAmount', type: ABIDataTypes.UINT256 },
            { name: 'netAmount', type: ABIDataTypes.UINT256 },
            { name: 'voucherId', type: ABIDataTypes.UINT256 },
            { name: 'signerEpoch', type: ABIDataTypes.UINT32 },
        ],
        type: BitcoinAbiTypes.Event,
    },
];

export const BridgeDepositoryAbi = [
    {
        name: 'addWrappedToken',
        inputs: [{ name: 'wrappedToken', type: ABIDataTypes.ADDRESS }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'removeWrappedToken',
        inputs: [{ name: 'wrappedToken', type: ABIDataTypes.ADDRESS }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isWrappedToken',
        constant: true,
        inputs: [],
        outputs: [{ name: 'enabled', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'rotateSigner',
        inputs: [{ name: 'signerPubKey', type: ABIDataTypes.BYTES }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setInitialSigner',
        inputs: [{ name: 'signerPubKey', type: ABIDataTypes.BYTES }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'cancelVoucher',
        inputs: [{ name: 'voucherId', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isVoucherCancelled',
        constant: true,
        inputs: [],
        outputs: [{ name: 'cancelled', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setAuthorityAddress',
        inputs: [{ name: 'authority', type: ABIDataTypes.ADDRESS }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setUpgradeAuthority',
        inputs: [{ name: 'newUpgradeAuthority', type: ABIDataTypes.ADDRESS }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'proposeUpgrade',
        inputs: [],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'cancelProposedUpgrade',
        inputs: [],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'upgradeAuthority',
        constant: true,
        inputs: [],
        outputs: [{ name: 'upgradeAuthority', type: ABIDataTypes.ADDRESS }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'pendingUpgradeAuthorized',
        constant: true,
        inputs: [],
        outputs: [{ name: 'pendingUpgradeAuthorized', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setWrapFeeBps',
        inputs: [{ name: 'bps', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setWrapMinFee',
        inputs: [
            { name: 'wrappedToken', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'wrapFeeBps',
        constant: true,
        inputs: [],
        outputs: [{ name: 'bps', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'wrapMinFee',
        constant: true,
        inputs: [],
        outputs: [{ name: 'amount', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setTokenMode',
        inputs: [
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'mode', type: ABIDataTypes.UINT256 },
            { name: 'evmCounterpart', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'tokenMode',
        constant: true,
        inputs: [],
        outputs: [{ name: 'mode', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'evmCounterpartOf',
        constant: true,
        inputs: [],
        outputs: [{ name: 'counterpart', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'computeFlowId',
        inputs: [
            { name: 'mode', type: ABIDataTypes.UINT256 },
            { name: 'evmChainId', type: ABIDataTypes.UINT256 },
            { name: 'evmBridge', type: ABIDataTypes.UINT256 },
            { name: 'evmToken', type: ABIDataTypes.UINT256 },
            { name: 'opnetBridge', type: ABIDataTypes.UINT256 },
            { name: 'opnetToken', type: ABIDataTypes.UINT256 },
        ],
        outputs: [{ name: 'flowId', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'addFlow',
        inputs: [
            { name: 'mode', type: ABIDataTypes.UINT256 },
            { name: 'evmChainId', type: ABIDataTypes.UINT256 },
            { name: 'evmBridge', type: ABIDataTypes.UINT256 },
            { name: 'evmToken', type: ABIDataTypes.UINT256 },
            { name: 'evmDecimals', type: ABIDataTypes.UINT256 },
            { name: 'opnetBridge', type: ABIDataTypes.UINT256 },
            { name: 'opnetToken', type: ABIDataTypes.UINT256 },
            { name: 'opnetDecimals', type: ABIDataTypes.UINT256 },
            { name: 'feeBps', type: ABIDataTypes.UINT256 },
            { name: 'minFee', type: ABIDataTypes.UINT256 },
            { name: 'minAmount', type: ABIDataTypes.UINT256 },
            { name: 'cap', type: ABIDataTypes.UINT256 },
            { name: 'dailyLimit', type: ABIDataTypes.UINT256 },
            { name: 'tipCapBps', type: ABIDataTypes.UINT256 },
        ],
        outputs: [{ name: 'flowId', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'pauseFlow',
        inputs: [{ name: 'flowId', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'resumeFlow',
        inputs: [{ name: 'flowId', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'drainFlow',
        inputs: [{ name: 'flowId', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setFlowCap',
        inputs: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'newCap', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setFlowDailyLimit',
        inputs: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'newLimit', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setFlowMinAmount',
        inputs: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'newMin', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setFlowFee',
        inputs: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'newBps', type: ABIDataTypes.UINT256 },
            { name: 'newMinFee', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setFlowTipCap',
        inputs: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'newBps', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'flowExists',
        constant: true,
        inputs: [],
        outputs: [{ name: 'exists', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'flowCount',
        constant: true,
        inputs: [],
        outputs: [{ name: 'count', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'getFlow',
        constant: true,
        inputs: [],
        outputs: [{ name: 'flow', type: ABIDataTypes.BYTES }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'lockForBridge',
        inputs: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'canonicalToken', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
            { name: 'evmRecipient', type: ABIDataTypes.BYTES32 },
            { name: 'destChainId', type: ABIDataTypes.UINT32 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'claimReleaseWithVoucher',
        inputs: [
            { name: 'voucher', type: ABIDataTypes.BYTES },
            { name: 'mldsaSig', type: ABIDataTypes.BYTES },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'provisionInventoryOpNet',
        inputs: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'drainInventoryOpNet',
        inputs: [
            { name: 'flowId', type: ABIDataTypes.UINT256 },
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
            { name: 'recipient', type: ABIDataTypes.ADDRESS },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'addSignerToSet',
        inputs: [{ name: 'pubKeyHash', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'removeSignerFromSet',
        inputs: [{ name: 'pubKeyHash', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setRequiredSignatures',
        inputs: [{ name: 'threshold', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'migrateSignerSet',
        inputs: [{ name: 'payload', type: ABIDataTypes.BYTES }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'confirmBurn',
        inputs: [
            { name: 'depositId', type: ABIDataTypes.UINT256 },
            { name: 'attestation', type: ABIDataTypes.BYTES },
            { name: 'mldsaSig', type: ABIDataTypes.BYTES },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isBurnConfirmed',
        constant: true,
        inputs: [],
        outputs: [{ name: 'confirmed', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'authorityAddress',
        constant: true,
        inputs: [],
        outputs: [{ name: 'authority', type: ABIDataTypes.ADDRESS }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'signerCount',
        constant: true,
        inputs: [],
        outputs: [{ name: 'count', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'requiredSignatures',
        constant: true,
        inputs: [],
        outputs: [{ name: 'threshold', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isSignerAuthorized',
        constant: true,
        inputs: [],
        outputs: [{ name: 'authorized', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setPaused',
        inputs: [{ name: 'paused', type: ABIDataTypes.BOOL }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setGovernor',
        inputs: [{ name: 'newGovernor', type: ABIDataTypes.ADDRESS }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'claimMintWithVoucher',
        inputs: [
            { name: 'voucher', type: ABIDataTypes.BYTES },
            { name: 'mldsaSig', type: ABIDataTypes.BYTES },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'governor',
        constant: true,
        inputs: [],
        outputs: [{ name: 'governor', type: ABIDataTypes.ADDRESS }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'paused',
        constant: true,
        inputs: [],
        outputs: [{ name: 'paused', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'signerEpoch',
        constant: true,
        inputs: [],
        outputs: [{ name: 'signerEpoch', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'signerHashAtEpoch',
        constant: true,
        inputs: [],
        outputs: [{ name: 'signerHash', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isVoucherUsed',
        constant: true,
        inputs: [],
        outputs: [{ name: 'used', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isSourceEventUsed',
        constant: true,
        inputs: [],
        outputs: [{ name: 'used', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'storageVersion',
        constant: true,
        inputs: [],
        outputs: [{ name: 'storageVersion', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'networkId',
        constant: true,
        inputs: [],
        outputs: [{ name: 'networkId', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    ...BridgeDepositoryEvents,
    ...OP_NET_ABI,
];

export default BridgeDepositoryAbi;
