import { ABIDataTypes, BitcoinAbiTypes, OP_NET_ABI } from 'opnet';

export const BridgeDepositoryEvents = [
    {
        name: 'WrappedTokenSet',
        values: [
            { name: 'wrappedToken', type: ABIDataTypes.ADDRESS },
            { name: 'enabled', type: ABIDataTypes.BOOL },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'SignerRotated',
        values: [
            { name: 'oldEpoch', type: ABIDataTypes.UINT32 },
            { name: 'newEpoch', type: ABIDataTypes.UINT32 },
            { name: 'newSignerHash', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'TokenModeSet',
        values: [
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'mode', type: ABIDataTypes.UINT32 },
            { name: 'evmCounterpart', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'LockedForBridge',
        values: [
            { name: 'canonicalToken', type: ABIDataTypes.ADDRESS },
            { name: 'user', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
            { name: 'evmRecipient', type: ABIDataTypes.UINT256 },
            { name: 'destChainId', type: ABIDataTypes.UINT32 },
            { name: 'lockNonce', type: ABIDataTypes.UINT256 },
            { name: 'mode', type: ABIDataTypes.UINT32 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'ReleasedFromVoucher',
        values: [
            { name: 'recipient', type: ABIDataTypes.ADDRESS },
            { name: 'canonicalToken', type: ABIDataTypes.ADDRESS },
            { name: 'sourceChainId', type: ABIDataTypes.UINT256 },
            { name: 'sourceTxHash', type: ABIDataTypes.UINT256 },
            { name: 'sourceLogIndex', type: ABIDataTypes.UINT32 },
            { name: 'grossAmount', type: ABIDataTypes.UINT256 },
            { name: 'feeAmount', type: ABIDataTypes.UINT256 },
            { name: 'netAmount', type: ABIDataTypes.UINT256 },
            { name: 'voucherId', type: ABIDataTypes.UINT256 },
            { name: 'signerEpoch', type: ABIDataTypes.UINT32 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'InventoryProvisionedOpNet',
        values: [
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'by', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'InventoryDrainedOpNet',
        values: [
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'to', type: ABIDataTypes.ADDRESS },
            { name: 'by', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'Paused',
        values: [],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'Unpaused',
        values: [],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'GovernorUpdated',
        values: [
            { name: 'oldGov', type: ABIDataTypes.ADDRESS },
            { name: 'newGov', type: ABIDataTypes.ADDRESS },
        ],
        type: BitcoinAbiTypes.Event,
    },
    {
        name: 'MintedFromVoucher',
        values: [
            { name: 'recipient', type: ABIDataTypes.ADDRESS },
            { name: 'wrappedToken', type: ABIDataTypes.ADDRESS },
            { name: 'sourceChainId', type: ABIDataTypes.UINT256 },
            { name: 'sourceTxHash', type: ABIDataTypes.UINT256 },
            { name: 'sourceLogIndex', type: ABIDataTypes.UINT32 },
            { name: 'grossAmount', type: ABIDataTypes.UINT256 },
            { name: 'feeAmount', type: ABIDataTypes.UINT256 },
            { name: 'netAmount', type: ABIDataTypes.UINT256 },
            { name: 'voucherId', type: ABIDataTypes.UINT256 },
            { name: 'signerEpoch', type: ABIDataTypes.UINT32 },
        ],
        type: BitcoinAbiTypes.Event,
    },
];

export const BridgeDepositoryAbi = [
    {
        name: 'addWrappedToken',
        inputs: [{ name: 'wrappedToken', type: ABIDataTypes.ADDRESS }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'removeWrappedToken',
        inputs: [{ name: 'wrappedToken', type: ABIDataTypes.ADDRESS }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isWrappedToken',
        constant: true,
        inputs: [],
        outputs: [{ name: 'enabled', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'rotateSigner',
        inputs: [{ name: 'signerPubKey', type: ABIDataTypes.BYTES }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setInitialSigner',
        inputs: [{ name: 'signerPubKey', type: ABIDataTypes.BYTES }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'cancelVoucher',
        inputs: [{ name: 'voucherId', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isVoucherCancelled',
        constant: true,
        inputs: [],
        outputs: [{ name: 'cancelled', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setAuthorityAddress',
        inputs: [{ name: 'authority', type: ABIDataTypes.ADDRESS }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setWrapFeeBps',
        inputs: [{ name: 'bps', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setWrapMinFee',
        inputs: [
            { name: 'wrappedToken', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'wrapFeeBps',
        constant: true,
        inputs: [],
        outputs: [{ name: 'bps', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'wrapMinFee',
        constant: true,
        inputs: [],
        outputs: [{ name: 'amount', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setTokenMode',
        inputs: [
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'mode', type: ABIDataTypes.UINT256 },
            { name: 'evmCounterpart', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'tokenMode',
        constant: true,
        inputs: [],
        outputs: [{ name: 'mode', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'evmCounterpartOf',
        constant: true,
        inputs: [],
        outputs: [{ name: 'counterpart', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'lockForBridge',
        inputs: [
            { name: 'canonicalToken', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
            { name: 'evmRecipient', type: ABIDataTypes.BYTES32 },
            { name: 'destChainId', type: ABIDataTypes.UINT32 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'claimReleaseWithVoucher',
        inputs: [
            { name: 'voucher', type: ABIDataTypes.BYTES },
            { name: 'mldsaSig', type: ABIDataTypes.BYTES },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'provisionInventoryOpNet',
        inputs: [
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'drainInventoryOpNet',
        inputs: [
            { name: 'token', type: ABIDataTypes.ADDRESS },
            { name: 'amount', type: ABIDataTypes.UINT256 },
            { name: 'recipient', type: ABIDataTypes.ADDRESS },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'addSignerToSet',
        inputs: [{ name: 'pubKeyHash', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'removeSignerFromSet',
        inputs: [{ name: 'pubKeyHash', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setRequiredSignatures',
        inputs: [{ name: 'threshold', type: ABIDataTypes.UINT256 }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'authorityAddress',
        constant: true,
        inputs: [],
        outputs: [{ name: 'authority', type: ABIDataTypes.ADDRESS }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'signerCount',
        constant: true,
        inputs: [],
        outputs: [{ name: 'count', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'requiredSignatures',
        constant: true,
        inputs: [],
        outputs: [{ name: 'threshold', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isSignerAuthorized',
        constant: true,
        inputs: [],
        outputs: [{ name: 'authorized', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setPaused',
        inputs: [{ name: 'paused', type: ABIDataTypes.BOOL }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'setGovernor',
        inputs: [{ name: 'newGovernor', type: ABIDataTypes.ADDRESS }],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'claimMintWithVoucher',
        inputs: [
            { name: 'voucher', type: ABIDataTypes.BYTES },
            { name: 'mldsaSig', type: ABIDataTypes.BYTES },
        ],
        outputs: [],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'governor',
        constant: true,
        inputs: [],
        outputs: [{ name: 'governor', type: ABIDataTypes.ADDRESS }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'paused',
        constant: true,
        inputs: [],
        outputs: [{ name: 'paused', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'signerEpoch',
        constant: true,
        inputs: [],
        outputs: [{ name: 'signerEpoch', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'signerHashAtEpoch',
        constant: true,
        inputs: [],
        outputs: [{ name: 'signerHash', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isVoucherUsed',
        constant: true,
        inputs: [],
        outputs: [{ name: 'used', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'isSourceEventUsed',
        constant: true,
        inputs: [],
        outputs: [{ name: 'used', type: ABIDataTypes.BOOL }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'storageVersion',
        constant: true,
        inputs: [],
        outputs: [{ name: 'storageVersion', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    {
        name: 'networkId',
        constant: true,
        inputs: [],
        outputs: [{ name: 'networkId', type: ABIDataTypes.UINT256 }],
        type: BitcoinAbiTypes.Function,
    },
    ...BridgeDepositoryEvents,
    ...OP_NET_ABI,
];

export default BridgeDepositoryAbi;
